language: python

sudo: required

matrix:
    include:
        - python: '2.5'
        - python: '2.6'
        - python: '2.7'
    allow_failures:
        - python: '2.5'
    fast_finish: true

cache:
    pip: true

before_install:
    - set -e  # fail on any error
    - sudo apt-get update -q
    - set -x; sudo apt-get install -y -q mpich libmpich-dev

install:
    - python setup.py build && python setup.py install

script:
    - for test in tests/*.py; do echo $test ; python $test > /dev/null ; done
